<?php
include 'db.php';
require('fpdf.php');

$month_start = date('Y-m-01');
$month_end = date('Y-m-t');
$department = $_GET['department'] ?? '';
$role = $_GET['role'] ?? '';

$condition = "vote_date BETWEEN '$month_start' AND '$month_end'";
if ($department && $department != 'All') {
    $condition .= " AND e.department = '$department'";
}
if ($role && $role != 'All') {
    $condition .= " AND e.role = '$role'";
}

$query = $conn->query("
  SELECT v.vote_date,
         SUM(CASE WHEN v.mood = 'happy' THEN 1 ELSE 0 END) as happy,
         SUM(CASE WHEN v.mood = 'sad' THEN 1 ELSE 0 END) as sad
  FROM votes v
  JOIN employees e ON v.employee_id = e.employee_id
  WHERE $condition
  GROUP BY v.vote_date
  ORDER BY v.vote_date
");

// Generate CSV
$csv_filename = "monthly_vote_report_" . date('Y_m') . ".csv";
$csv_path = "/tmp/" . $csv_filename;
$fp = fopen($csv_path, 'w');
fputcsv($fp, ['Date', 'Happy', 'Sad']);
$data = [];

while ($row = $query->fetch_assoc()) {
    fputcsv($fp, [$row['vote_date'], $row['happy'], $row['sad']]);
    $data[] = $row;
}
fclose($fp);

// Generate PDF
$pdf = new FPDF();
$pdf->AddPage();
$pdf->Image($_SERVER['DOCUMENT_ROOT'] . '/Logo.jpg', 10, 6, 30); // Absolute path fix
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 20, 'Mövenpick Monthly Mood Voting Report', 0, 1, 'C');
$pdf->SetFont('Arial', '', 12);
$pdf->Ln(5);
foreach ($data as $row) {
    $pdf->Cell(0, 10, "{$row['vote_date']} - 😊 Happy: {$row['happy']}, 😞 Sad: {$row['sad']}", 0, 1);
}
$pdf->Ln(10);
$pdf->Image($_SERVER['DOCUMENT_ROOT'] . '/Logo.jpg', 10, 230, 20); // Signature logo bottom
$pdf->SetFont('Arial', 'I', 10);
$pdf->SetY(-30);
$pdf->Cell(0, 10, 'Report generated by Mövenpick Feedback System', 0, 1, 'C');
$pdf->Cell(0, 10, 'Signature: __________________________', 0, 1, 'R');

$pdf_path = "/tmp/monthly_vote_report.pdf";
$pdf->Output('F', $pdf_path);

// Email
$to = "Udara.silva@movenpick.com";
$subject = "Monthly Voting Report";
$boundary = md5("multipartboundary");
$headers = "From: noreply@yourdomain.com
";
$headers .= "MIME-Version: 1.0
";
$headers .= "Content-Type: multipart/mixed; boundary="$boundary"
";

$message = "--$boundary
";
$message .= "Content-Type: text/plain; charset=UTF-8

";
$message .= "Attached are the monthly mood voting reports for your review.
";

// CSV
$file_data = chunk_split(base64_encode(file_get_contents($csv_path)));
$message .= "--$boundary
";
$message .= "Content-Type: text/csv; name="$csv_filename"
";
$message .= "Content-Disposition: attachment; filename="$csv_filename"
";
$message .= "Content-Transfer-Encoding: base64

$file_data
";

// PDF
$file_data = chunk_split(base64_encode(file_get_contents($pdf_path)));
$message .= "--$boundary
";
$message .= "Content-Type: application/pdf; name="monthly_vote_report.pdf"
";
$message .= "Content-Disposition: attachment; filename="monthly_vote_report.pdf"
";
$message .= "Content-Transfer-Encoding: base64

$file_data
";
$message .= "--$boundary--";

mail($to, $subject, $message, $headers);
echo "Monthly report sent to Udara.silva@movenpick.com";
?>
